### ISSUE TITLE
Improve stylesheet for components sourceDisplay, sourceInput

### ISSUE THREAD

**Issue by joewrotehaikus** [joewrotehaikus/mnemefeast#1]
I recommend a mobile-first approach, but it should be designed for all screen widths.

**Comment by rezbee-dev** [comment]
I can try to do this
Will give an update by end of day

**Comment by joewrotehaikus** [comment]
> I can try to do this Will give an update by end of day

If you like the look you made, you're probably better at design than I am anyway.
